version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: quickdoc-backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./database:/app/database 
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: quickdoc-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:14-alpine
    container_name: quickdoc-db
    restart: always
    environment:
      POSTGRES_DB: quickdoc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
