# docker-compose.dev.yml
version: '3.9'

services:
  # ───────────────────────────────────────────────
  # Flask backend (dev — hot reload + auto-migrations)
  # ───────────────────────────────────────────────
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        FLASK_ENV: development
    container_name: quickdoc-backend-dev
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./backend/instance:/app/instance
    environment:
      FLASK_ENV: development
      FLASK_APP: app:create_app
      FLASK_DEBUG: "1"
    command: >
      sh -c "
        # 1) flask db init if needed (ignore errors on rerun)
        flask db init 2>/dev/null || true &&
        # 2) autogenerate any missing migrations
        flask db migrate -m 'auto schema' 2>/dev/null || true &&
        # 3) apply all migrations
        flask db upgrade &&
        # 4) finally start Flask
        flask run --host=0.0.0.0 --port=5000 --reload
      "
    ports:
      - "5000:5000"
    depends_on:
      - db

  # ───────────────────────────────────────────────
  # React frontend (dev — hot reload)
  # ───────────────────────────────────────────────
  frontend:
    image: node:18-alpine
    container_name: quickdoc-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
      BROWSER: none
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - backend

  # ───────────────────────────────────────────────
  # Postgres (dev)
  # ───────────────────────────────────────────────
  db:
    image: postgres:14-alpine
    container_name: quickdoc-db-dev
    restart: always
    environment:
      POSTGRES_DB: quickdoc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

volumes:
  pgdata_dev:
