"""create slot_confirmations table

Revision ID: 66490c9ce1fd
Revises: 
Create Date: 2025-07-08 03:06:47.305296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66490c9ce1fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_confirmations',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('standby_preferences', schema=None) as batch_op:
        batch_op.drop_column('specialty')
        batch_op.drop_column('start_date')
        batch_op.drop_column('city')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standby_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    op.drop_table('slot_confirmations')
    # ### end Alembic commands ###
